In [45]:
import pandas as pd
import numpy as np

In [46]:
# compute mean of a specified attribute across a specified region 
def get_mean_for_region(region,attribute,climate_df):
    return climate_df.groupby('Prov_or_Ter')[attribute].mean()[region]

In [47]:
all_processed_df = pd.DataFrame() # df to store processed results 

# iterate through each month and add processed data to all_processed_df
for year in range(2001,2024):
    for month in range(1,13):
        month = f'{month:>02}'  # to get months as 01, 02, 03, etc

        print("Processing",month,year)
        climate_df = pd.read_csv(f"./datasets/raw/climate_data/en_climate_summaries_All_{month}-{year}.csv") # read raw Monthly Climate Summary data
        climate_df.drop(['DwTm', 'DwTx', 'DwTn', 'DwS', 'DwP', 'DwBS'],axis=1,inplace=True) # drop columns not needed
        climate_df.drop(climate_df[climate_df["Prov_or_Ter"].isin(['NT','NU','YT','NL','NS','NB','PE'])].index, inplace=True) # drop provinces not included
        climate_df['P'] = climate_df['P'].replace('######',np.nan).replace('',np.nan).astype(float) # replace missing data with nan 
        climate_df['S%N'] = climate_df['S%N'].replace('######',np.nan).replace('',np.nan).astype(float)
        climate_df['P%N'] = climate_df['P%N'].replace('######',np.nan).replace('',np.nan).astype(float)

        processed_df = pd.DataFrame()
        processed_df['Province'] = climate_df['Prov_or_Ter'].unique()
        # compute mean of each attribute for each province
        processed_df['Tm'] = processed_df['Province'].apply(get_mean_for_region,args=('Tm',climate_df))
        processed_df['Tn'] = processed_df['Province'].apply(get_mean_for_region,args=('Tn',climate_df))
        processed_df['Tx'] = processed_df['Province'].apply(get_mean_for_region,args=('Tx',climate_df))
        processed_df['D'] = processed_df['Province'].apply(get_mean_for_region,args=('D',climate_df))
        processed_df['S'] = processed_df['Province'].apply(get_mean_for_region,args=('S',climate_df))
        processed_df['S%N'] = processed_df['Province'].apply(get_mean_for_region,args=('S%N',climate_df))
        processed_df['P'] = processed_df['Province'].apply(get_mean_for_region,args=('P',climate_df))
        processed_df['P%N'] = processed_df['Province'].apply(get_mean_for_region,args=('P%N',climate_df))
        processed_df['S_G'] = processed_df['Province'].apply(get_mean_for_region,args=('S_G',climate_df))
        processed_df['Pd'] = processed_df['Province'].apply(get_mean_for_region,args=('Pd',climate_df))
        processed_df['BS'] = processed_df['Province'].apply(get_mean_for_region,args=('BS',climate_df))
        processed_df['BS%'] = processed_df['Province'].apply(get_mean_for_region,args=('BS%',climate_df))
        processed_df['HDD'] = processed_df['Province'].apply(get_mean_for_region,args=('HDD',climate_df))
        processed_df['CDD'] = processed_df['Province'].apply(get_mean_for_region,args=('CDD',climate_df))
        processed_df['Month'] = f'{year}-{month}'

        cols = processed_df.columns.tolist()
        cols = cols[-1:] + cols[:-1]

        processed_df = processed_df[cols] # move month to start of list
        all_processed_df = pd.concat([all_processed_df,processed_df])        

all_processed_df.head()

Processing 01 2001
Processing 02 2001
Processing 03 2001
Processing 04 2001

Processing 05 2001
Processing 06 2001
Processing 07 2001
Processing 08 2001
Processing 09 2001
Processing 10 2001
Processing 11 2001
Processing 12 2001
Processing 01 2002
Processing 02 2002
Processing 03 2002
Processing 04 2002
Processing 05 2002
Processing 06 2002
Processing 07 2002
Processing 08 2002
Processing 09 2002
Processing 10 2002
Processing 11 2002
Processing 12 2002
Processing 01 2003
Processing 02 2003
Processing 03 2003
Processing 04 2003
Processing 05 2003
Processing 06 2003
Processing 07 2003
Processing 08 2003
Processing 09 2003
Processing 10 2003
Processing 11 2003
Processing 12 2003
Processing 01 2004
Processing 02 2004
Processing 03 2004
Processing 04 2004
Processing 05 2004
Processing 06 2004
Processing 07 2004
Processing 08 2004
Processing 09 2004
Processing 10 2004
Processing 11 2004
Processing 12 2004
Processing 01 2005
Processing 02 2005
Processing 03 2005
Processing 04 2005
Processing 05 2005
Processing 06 2005
Processing 07 2005
Processing 08 2005
Processing 09 2005
Processing 10 2005
Processing 11 2005
Processing 12 2005
Processing 01 2006
Processing 02 2006
Processing 03 2006
Processing 04 2006
Processing 05 2006
Processing 06 2006
Processing 07 2006
Processing 08 2006
Processing 09 2006
Processing 10 2006
Processing 11 2006
Processing 12 2006
Processing 01 2007
Processing 02 2007
Processing 03 2007
Processing 04 2007
Processing 05 2007
Processing 06 2007
Processing 07 2007
Processing 08 2007
Processing 09 2007
Processing 10 2007
Processing 11 2007
Processing 12 2007
Processing 01 2008
Processing 02 2008
Processing 03 2008
Processing 04 2008
Processing 05 2008
Processing 06 2008
Processing 07 2008
Processing 08 2008
Processing 09 2008
Processing 10 2008
Processing 11 2008
Processing 12 2008
Processing 01 2009
Processing 02 2009
Processing 03 2009
Processing 04 2009
Processing 05 2009
Processing 06 2009
Processing 07 2009
Processing 08 2009
Processing 09 2009
Processing 10 2009
Processing 11 2009
Processing 12 2009
Processing 01 2010
Processing 02 2010
Processing 03 2010
Processing 04 2010
Processing 05 2010
Processing 06 2010
Processing 07 2010
Processing 08 2010
Processing 09 2010
Processing 10 2010
Processing 11 2010
Processing 12 2010
Processing 01 2011
Processing 02 2011
Processing 03 2011
Processing 04 2011
Processing 05 2011
Processing 06 2011
Processing 07 2011
Processing 08 2011
Processing 09 2011
Processing 10 2011
Processing 11 2011
Processing 12 2011
Processing 01 2012
Processing 02 2012
Processing 03 2012
Processing 04 2012
Processing 05 2012
Processing 06 2012
Processing 07 2012
Processing 08 2012
Processing 09 2012
Processing 10 2012
Processing 11 2012
Processing 12 2012
Processing 01 2013
Processing 02 2013
Processing 03 2013
Processing 04 2013
Processing 05 2013
Processing 06 2013
Processing 07 2013
Processing 08 2013
Processing 09 2013
Processing 10 2013
Processing 11 2013
Processing 12 2013
Processing 01 2014
Processing 02 2014
Processing 03 2014
Processing 04 2014
Processing 05 2014
Processing 06 2014
Processing 07 2014
Processing 08 2014
Processing 09 2014
Processing 10 2014
Processing 11 2014
Processing 12 2014
Processing 01 2015
Processing 02 2015
Processing 03 2015
Processing 04 2015
Processing 05 2015
Processing 06 2015
Processing 07 2015
Processing 08 2015
Processing 09 2015
Processing 10 2015
Processing 11 2015
Processing 12 2015
Processing 01 2016
Processing 02 2016
Processing 03 2016
Processing 04 2016
Processing 05 2016
Processing 06 2016
Processing 07 2016
Processing 08 2016
Processing 09 2016
Processing 10 2016
Processing 11 2016
Processing 12 2016
Processing 01 2017
Processing 02 2017
Processing 03 2017
Processing 04 2017
Processing 05 2017
Processing 06 2017
Processing 07 2017
Processing 08 2017
Processing 09 2017
Processing 10 2017
Processing 11 2017
Processing 12 2017
Processing 01 2018
Processing 02 2018
Processing 03 2018
Processing 04 2018
Processing 05 2018
Processing 06 2018
Processing 07 2018
Processing 08 2018
Processing 09 2018
Processing 10 2018
Processing 11 2018
Processing 12 2018
Processing 01 2019
Processing 02 2019
Processing 03 2019
Processing 04 2019
Processing 05 2019
Processing 06 2019
Processing 07 2019
Processing 08 2019
Processing 09 2019
Processing 10 2019
Processing 11 2019
Processing 12 2019
Processing 01 2020
Processing 02 2020
Processing 03 2020
Processing 04 2020
Processing 05 2020
Processing 06 2020
Processing 07 2020
Processing 08 2020
Processing 09 2020
Processing 10 2020
Processing 11 2020
Processing 12 2020
Processing 01 2021
Processing 02 2021
Processing 03 2021
Processing 04 2021
Processing 05 2021
Processing 06 2021
Processing 07 2021
Processing 08 2021
Processing 09 2021
Processing 10 2021
Processing 11 2021
Processing 12 2021
Processing 01 2022
Processing 02 2022
Processing 03 2022
Processing 04 2022
Processing 05 2022
Processing 06 2022
Processing 07 2022
Processing 08 2022
Processing 09 2022
Processing 10 2022
Processing 11 2022
Processing 12 2022
Processing 01 2023
Processing 02 2023
Processing 03 2023
Processing 04 2023
Processing 05 2023
Processing 06 2023
Processing 07 2023
Processing 08 2023
Processing 09 2023
Processing 10 2023
Processing 11 2023
Processing 12 2023

,Month,Province,Tm,Tn,Tx,D,S,S%N,P,P%N,S_G,Pd,BS,BS%,HDD,CDD
0,2001-01,BC,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,47.826667,92.857143,519.116812,0.0
1,2001-01,AB,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,105.425000,117.428571,683.534310,0.0
2,2001-01,SK,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,116.233333,118.500000,824.227632,0.0
3,2001-01,MB,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,80.857143,84.571429,931.437607,0.0
4,2001-01,ON,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,61.793750,76.538462,756.844017,0.0

In [48]:
# rename columns
renamed_columns = {
    'Tm': 'Mean_Temp', 
    'Tn': 'Min_Temp',
    'Tx': 'Max_Temp',
    'D': 'Mean_Diff_from_Normal',
    'S': 'Snowfall',
    'S%N': 'Percent_of_Normal_Snowfall',
    'P': 'Total_Precip',
    'P%N': 'Percent_of_Normal_Precip',
    'S_G': 'Snow_on_Ground',
    'Pd': 'Days_with_Precip',
    'BS': 'Bright_Sunshine_Days',
    'BS%': 'Percent_of_Normal_Bright_Sunshine',
    'HDD': 'Heating_Degree_Days',
    'CDD': 'Cooling_Degree_Days',
}
all_processed_df.rename(columns=renamed_columns, inplace=True)

In [49]:
all_processed_df.head(10)

,Month,Province,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,Bright_Sunshine_Days,Percent_of_Normal_Bright_Sunshine,Heating_Degree_Days,Cooling_Degree_Days
0,2001-01,BC,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,47.826667,92.857143,519.116812,0.0
1,2001-01,AB,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,105.425000,117.428571,683.534310,0.0
2,2001-01,SK,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,116.233333,118.500000,824.227632,0.0
3,2001-01,MB,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,80.857143,84.571429,931.437607,0.0
4,2001-01,ON,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,61.793750,76.538462,756.844017,0.0
5,2001-01,QC,-11.848165,-27.704128,-0.005505,0.778947,46.938514,86.672269,43.582915,62.791667,44.892617,11.251256,78.418182,122.000000,904.394037,0.0
0,2001-02,BC,-1.307781,-13.054441,9.000000,-1.397990,15.914201,95.544248,47.262760,52.769912,18.104235,7.651042,105.620000,131.523810,526.445533,0.0
1,2001-02,AB,-12.235021,-30.208439,8.502532,-3.784694,16.217460,92.045045,15.730332,91.123894,12.285714,4.559242,126.933333,108.750000,829.360759,0.0
2,2001-02,SK,-17.148026,-34.496753,3.194156,-5.204902,11.060150,91.376147,10.781410,87.426087,32.785047,4.025641,125.011111,114.571429,983.901974,0.0
3,2001-02,MB,-18.767521,-35.649573,-1.538462,-4.688889,13.370435,88.353659,12.841667,81.620690,47.301370,4.681818,142.128571,115.714286,1016.544444,0.0

In [50]:

# identify columns with missing attributes
all_processed_df.isnull().sum(axis = 0)

Month                                   0
Province                                0
Mean_Temp                               0
Min_Temp                                0
Max_Temp                                0
Mean_Diff_from_Normal                   0
Snowfall                                0
Percent_of_Normal_Snowfall            133
Total_Precip                            0
Percent_of_Normal_Precip                0
Snow_on_Ground                          0
Days_with_Precip                        0
Bright_Sunshine_Days                  970
Percent_of_Normal_Bright_Sunshine    1034
Heating_Degree_Days                     0
Cooling_Degree_Days                     0
dtype: int64

In [51]:
# examine records with null 'Percent_of_Normal_Snowfall' values
pd.set_option('display.max_rows', 10)
all_processed_df[all_processed_df['Percent_of_Normal_Snowfall'].isnull()]

,Month,Province,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,Bright_Sunshine_Days,Percent_of_Normal_Bright_Sunshine,Heating_Degree_Days,Cooling_Degree_Days
4,2001-08,ON,20.705882,7.802092,34.581933,1.862097,0.0,NaN,67.999200,83.704000,0.000000,8.052000,243.155556,111.083333,13.444958,96.027311
4,2002-08,ON,19.875688,8.042466,31.880734,1.023009,0.0,NaN,48.264192,58.447368,0.000000,6.126638,255.264286,112.555556,19.259174,76.976606
4,2003-08,ON,20.123474,6.841784,30.916432,1.274074,0.0,NaN,78.631416,95.574074,0.000000,8.477876,90.450000,NaN,19.194366,83.791549
4,2004-08,ON,17.163158,5.175120,28.348571,-1.578846,0.0,NaN,73.681818,89.596154,0.000000,9.590909,242.300000,94.166667,59.804785,33.696651
4,2005-08,ON,20.108738,8.021256,31.905825,1.405208,0.0,NaN,80.449774,106.673684,0.000000,8.692308,246.500000,103.333333,17.764078,82.006796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,2023-07,QC,18.068889,7.993333,30.870476,1.800000,0.0,NaN,147.157055,179.416667,0.000000,12.564417,NaN,NaN,47.913333,51.867407
0,2023-08,BC,18.361321,7.709906,31.405140,1.716949,0.0,NaN,32.328934,66.666667,0.012821,4.497462,NaN,NaN,34.571698,44.233962
3,2023-08,MB,17.606452,5.904762,29.788710,0.550000,0.0,NaN,46.860000,69.750000,0.000000,6.800000,NaN,NaN,40.701613,30.403226
4,2023-08,ON,17.664634,5.695122,28.050000,-0.656000,0.0,NaN,84.843506,117.625000,0.000000,8.974026,NaN,NaN,39.761585,29.334146
5,2023-08,QC,15.493382,5.659906,25.919340,-0.500000,0.0,NaN,122.065031,153.125000,0.000000,11.447853,NaN,NaN,82.285294,10.672794

In [52]:
# examine records with null 'Percent_of_Normal_Snowfall' values
all_processed_df[all_processed_df['Bright_Sunshine_Days'].isnull()][['Month','Province','Bright_Sunshine_Days','Percent_of_Normal_Bright_Sunshine']]

      Month Province  Bright_Sunshine_Days  Percent_of_Normal_Bright_Sunshine
3   2006-04       MB                   NaN                                NaN
3   2006-05       MB                   NaN                                NaN
3   2006-06       MB                   NaN                                NaN
3   2006-07       MB                   NaN                                NaN
3   2006-10       MB                   NaN                                NaN
..      ...      ...                   ...                                ...
1   2023-12       AB                   NaN                                NaN
2   2023-12       SK                   NaN                                NaN
3   2023-12       MB                   NaN                                NaN
4   2023-12       ON                   NaN                                NaN
5   2023-12       QC                   NaN                                NaN

[970 rows x 4 columns]

In [53]:
# Handle null values
# missing Percent_of_Normal_Snowfall are set to 0 as they occur in months of July and August where Snowfall is 0 
all_processed_df['Percent_of_Normal_Snowfall'].fillna(0,inplace=True)

C:\Users\daniel\AppData\Local\Temp\ipykernel_12912\334984458.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  all_processed_df['Percent_of_Normal_Snowfall'].fillna(0,inplace=True)

In [54]:
# dropping attributes with large number of missing values 
all_processed_df.drop(['Bright_Sunshine_Days','Percent_of_Normal_Bright_Sunshine'],axis=1,inplace=True)

In [55]:
# resetting index to use as surrogate key 
all_processed_df.reset_index(inplace=True)
all_processed_df.drop('index',axis=1,inplace=True)
all_processed_df.head(10)

,Month,Province,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,Heating_Degree_Days,Cooling_Degree_Days
0,2001-01,BC,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,519.116812,0.0
1,2001-01,AB,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,683.534310,0.0
2,2001-01,SK,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,824.227632,0.0
3,2001-01,MB,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,931.437607,0.0
4,2001-01,ON,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,756.844017,0.0
5,2001-01,QC,-11.848165,-27.704128,-0.005505,0.778947,46.938514,86.672269,43.582915,62.791667,44.892617,11.251256,904.394037,0.0
6,2001-02,BC,-1.307781,-13.054441,9.000000,-1.397990,15.914201,95.544248,47.262760,52.769912,18.104235,7.651042,526.445533,0.0
7,2001-02,AB,-12.235021,-30.208439,8.502532,-3.784694,16.217460,92.045045,15.730332,91.123894,12.285714,4.559242,829.360759,0.0
8,2001-02,SK,-17.148026,-34.496753,3.194156,-5.204902,11.060150,91.376147,10.781410,87.426087,32.785047,4.025641,983.901974,0.0
9,2001-02,MB,-18.767521,-35.649573,-1.538462,-4.688889,13.370435,88.353659,12.841667,81.620690,47.301370,4.681818,1016.544444,0.0

In [56]:
# verify that no null values remain
pd.set_option('display.max_rows', 2000)
all_processed_df.isnull().sum(axis = 0)

Month                         0
Province                      0
Mean_Temp                     0
Min_Temp                      0
Max_Temp                      0
Mean_Diff_from_Normal         0
Snowfall                      0
Percent_of_Normal_Snowfall    0
Total_Precip                  0
Percent_of_Normal_Precip      0
Snow_on_Ground                0
Days_with_Precip              0
Heating_Degree_Days           0
Cooling_Degree_Days           0
dtype: int64

In [57]:
# drop month and province - not part of Climate dimension 
all_processed_df.drop(['Month','Province'],axis=1,inplace=True)

In [58]:
all_processed_df.dtypes

Mean_Temp                     float64
Min_Temp                      float64
Max_Temp                      float64
Mean_Diff_from_Normal         float64
Snowfall                      float64
Percent_of_Normal_Snowfall    float64
Total_Precip                  float64
Percent_of_Normal_Precip      float64
Snow_on_Ground                float64
Days_with_Precip              float64
Heating_Degree_Days           float64
Cooling_Degree_Days           float64
dtype: object

In [59]:
# add normalized attributes to be used for analysis 
normalized_df = (all_processed_df-all_processed_df.min())/(all_processed_df.max()-all_processed_df.min())
normalized_df.head()

,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,Heating_Degree_Days,Cooling_Degree_Days
0,0.526950,0.626772,0.357437,0.684518,0.184589,0.058090,0.395959,0.167324,0.249274,0.569108,0.415337,0.0
1,0.421183,0.449098,0.360611,0.928905,0.048484,0.026920,0.014200,0.039387,0.086473,0.061978,0.548671,0.0
2,0.328628,0.326324,0.262447,0.896271,0.064468,0.055636,0.019037,0.080804,0.365969,0.108724,0.662765,0.0
3,0.254209,0.242940,0.221211,0.858953,0.104841,0.070368,0.031243,0.113779,0.540115,0.170934,0.749707,0.0
4,0.359013,0.333758,0.226991,0.680153,0.420590,0.140772,0.167032,0.195749,0.458897,0.520658,0.608121,0.0

In [60]:
normalized_df.rename(columns=lambda x: x+"_Normalized",inplace=True)
normalized_df.head()

,Mean_Temp_Normalized,Min_Temp_Normalized,Max_Temp_Normalized,Mean_Diff_from_Normal_Normalized,Snowfall_Normalized,Percent_of_Normal_Snowfall_Normalized,Total_Precip_Normalized,Percent_of_Normal_Precip_Normalized,Snow_on_Ground_Normalized,Days_with_Precip_Normalized,Heating_Degree_Days_Normalized,Cooling_Degree_Days_Normalized
0,0.526950,0.626772,0.357437,0.684518,0.184589,0.058090,0.395959,0.167324,0.249274,0.569108,0.415337,0.0
1,0.421183,0.449098,0.360611,0.928905,0.048484,0.026920,0.014200,0.039387,0.086473,0.061978,0.548671,0.0
2,0.328628,0.326324,0.262447,0.896271,0.064468,0.055636,0.019037,0.080804,0.365969,0.108724,0.662765,0.0
3,0.254209,0.242940,0.221211,0.858953,0.104841,0.070368,0.031243,0.113779,0.540115,0.170934,0.749707,0.0
4,0.359013,0.333758,0.226991,0.680153,0.420590,0.140772,0.167032,0.195749,0.458897,0.520658,0.608121,0.0

In [61]:
all_processed_df = pd.concat([all_processed_df,normalized_df], axis=1)
all_processed_df.columns.name = 'Climate ID'
all_processed_df.head()

Climate ID,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,...,Max_Temp_Normalized,Mean_Diff_from_Normal_Normalized,Snowfall_Normalized,Percent_of_Normal_Snowfall_Normalized,Total_Precip_Normalized,Percent_of_Normal_Precip_Normalized,Snow_on_Ground_Normalized,Days_with_Precip_Normalized,Heating_Degree_Days_Normalized,Cooling_Degree_Days_Normalized
0,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,...,0.357437,0.684518,0.184589,0.058090,0.395959,0.167324,0.249274,0.569108,0.415337,0.0
1,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,...,0.360611,0.928905,0.048484,0.026920,0.014200,0.039387,0.086473,0.061978,0.548671,0.0
2,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,...,0.262447,0.896271,0.064468,0.055636,0.019037,0.080804,0.365969,0.108724,0.662765,0.0
3,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,...,0.221211,0.858953,0.104841,0.070368,0.031243,0.113779,0.540115,0.170934,0.749707,0.0
4,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,...,0.226991,0.680153,0.420590,0.140772,0.167032,0.195749,0.458897,0.520658,0.608121,0.0

In [62]:
import math

Adding Moving Average

In [63]:
for col in all_processed_df.columns:
    if not (col == 'Climate_ID') and "Normalized" not in col and "Rolling_Average" not in col:
        all_processed_df[col + '_Rolling_Average'] = all_processed_df[col].rolling(6).mean()
all_processed_df.head(10)

Climate ID,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,...,Max_Temp_Rolling_Average,Mean_Diff_from_Normal_Rolling_Average,Snowfall_Rolling_Average,Percent_of_Normal_Snowfall_Rolling_Average,Total_Precip_Rolling_Average,Percent_of_Normal_Precip_Rolling_Average,Snow_on_Ground_Rolling_Average,Days_with_Precip_Rolling_Average,Heating_Degree_Days_Rolling_Average,Cooling_Degree_Days_Rolling_Average
0,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-11.848165,-27.704128,-0.005505,0.778947,46.938514,86.672269,43.582915,62.791667,44.892617,11.251256,...,4.517095,3.874615,21.838473,50.869791,36.896270,50.237507,29.517159,6.948878,769.925736,0.0
6,-1.307781,-13.054441,9.000000,-1.397990,15.914201,95.544248,47.262760,52.769912,18.104235,7.651042,...,4.583377,3.326367,21.347250,60.779148,26.807078,48.513147,29.304877,6.304781,771.147189,0.0
7,-12.235021,-30.208439,8.502532,-3.784694,16.217460,92.045045,15.730332,91.123894,12.285714,4.559242,...,4.543283,1.534033,23.224469,73.332632,28.456601,60.029594,30.232126,6.767282,795.451597,0.0
8,-17.148026,-34.496753,3.194156,-5.204902,11.060150,91.376147,10.781410,87.426087,32.785047,4.025641,...,4.344257,-0.381994,23.969926,82.801384,29.066003,68.712678,30.954710,6.991347,822.063988,0.0
9,-18.767521,-35.649573,-1.538462,-4.688889,13.370435,88.353659,12.841667,81.620690,47.301370,4.681818,...,3.661351,-2.082788,24.412862,90.240985,29.475398,74.663025,31.840409,7.125817,836.248461,0.0

Binning

In [64]:
binned_df = pd.DataFrame()

for col in all_processed_df.columns:
    if not (col == 'Climate_ID') and "Normalized" not in col:
        print(col)
        # binned_df[col + '_Binned'] = pd.qcut(all_processed_df[col], q=math.sqrt(len(all_processed_df[col])))
        binned_df[col + '_Binned'] = pd.qcut(all_processed_df[col], q=math.ceil(math.sqrt(len(all_processed_df['Cooling_Degree_Days']))),duplicates='drop')
        binned_df[col + '_Binned_Encoded'] = pd.qcut(all_processed_df[col], q=math.ceil(math.sqrt(len(all_processed_df['Cooling_Degree_Days']))),duplicates='drop',labels=False)

binned_df.head(20)

Mean_Temp
Min_Temp
Max_Temp
Mean_Diff_from_Normal
Snowfall
Percent_of_Normal_Snowfall
Total_Precip
Percent_of_Normal_Precip
Snow_on_Ground
Days_with_Precip
Heating_Degree_Days
Cooling_Degree_Days
Mean_Temp_Rolling_Average
Min_Temp_Rolling_Average
Max_Temp_Rolling_Average
Mean_Diff_from_Normal_Rolling_Average
Snowfall_Rolling_Average
Percent_of_Normal_Snowfall_Rolling_Average
Total_Precip_Rolling_Average
Percent_of_Normal_Precip_Rolling_Average
Snow_on_Ground_Rolling_Average
Days_with_Precip_Rolling_Average
Heating_Degree_Days_Rolling_Average
Cooling_Degree_Days_Rolling_Average

,Mean_Temp_Binned,Mean_Temp_Binned_Encoded,Min_Temp_Binned,Min_Temp_Binned_Encoded,Max_Temp_Binned,Max_Temp_Binned_Encoded,Mean_Diff_from_Normal_Binned,Mean_Diff_from_Normal_Binned_Encoded,Snowfall_Binned,Snowfall_Binned_Encoded,...,Percent_of_Normal_Precip_Rolling_Average_Binned,Percent_of_Normal_Precip_Rolling_Average_Binned_Encoded,Snow_on_Ground_Rolling_Average_Binned,Snow_on_Ground_Rolling_Average_Binned_Encoded,Days_with_Precip_Rolling_Average_Binned,Days_with_Precip_Rolling_Average_Binned_Encoded,Heating_Degree_Days_Rolling_Average_Binned,Heating_Degree_Days_Rolling_Average_Binned_Encoded,Cooling_Degree_Days_Rolling_Average_Binned,Cooling_Degree_Days_Rolling_Average_Binned_Encoded
0,"(-0.788, 0.354]",14,"(-9.3, -8.327]",19,"(8.595, 9.173]",9,"(1.858, 2.002]",32,"(18.161, 19.788]",22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"(-5.42, -4.265]",10,"(-19.687, -17.857]",12,"(8.595, 9.173]",9,"(4.807, 8.447]",40,"(4.249, 5.509]",11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"(-9.294, -8.259]",6,"(-25.829, -24.569]",8,"(3.739, 4.741]",3,"(4.807, 8.447]",40,"(5.509, 6.688]",12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"(-12.906, -11.526]",3,"(-30.12, -28.838]",5,"(0.658, 2.712]",1,"(4.807, 8.447]",40,"(10.699, 11.794]",16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"(-7.488, -6.566]",8,"(-24.569, -23.007]",9,"(2.712, 3.739]",2,"(1.685, 1.858]",31,"(40.008, 45.292]",30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"(-12.906, -11.526]",3,"(-28.838, -27.314]",6,"(-7.256, 0.658]",0,"(0.7, 0.808]",23,"(45.292, 55.882]",31,...,"(48.512, 64.993]",0.0,"(29.056, 30.884]",32.0,"(6.844, 6.949]",9.0,"(754.343, 770.845]",35.0,"(-0.001, 0.00177]",0.0
6,"(-1.62, -0.788]",13,"(-14.259, -12.888]",15,"(8.595, 9.173]",9,"(-1.604, -1.355]",6,"(15.262, 17.018]",20,...,"(48.512, 64.993]",0.0,"(29.056, 30.884]",32.0,"(6.172, 6.363]",4.0,"(770.845, 789.351]",36.0,"(-0.001, 0.00177]",0.0
7,"(-12.906, -11.526]",3,"(-31.573, -30.12]",4,"(8.041, 8.595]",8,"(-4.901, -3.745]",1,"(15.262, 17.018]",20,...,"(48.512, 64.993]",0.0,"(29.056, 30.884]",32.0,"(6.758, 6.844]",8.0,"(789.351, 809.434]",37.0,"(-0.001, 0.00177]",0.0
8,"(-23.609, -16.875]",0,"(-34.882, -33.211]",2,"(2.712, 3.739]",2,"(-12.331999999999999, -4.901]",0,"(10.699, 11.794]",16,...,"(64.993, 69.087]",1.0,"(30.884, 36.73]",33.0,"(6.949, 7.026]",10.0,"(809.434, 827.44]",38.0,"(-0.001, 0.00177]",0.0
9,"(-23.609, -16.875]",0,"(-36.58, -34.882]",1,"(-7.256, 0.658]",0,"(-4.901, -3.745]",1,"(13.011, 14.151]",18,...,"(73.886, 76.676]",4.0,"(30.884, 36.73]",33.0,"(7.026, 7.13]",11.0,"(827.44, 862.842]",39.0,"(-0.001, 0.00177]",0.0
10,"(-7.488, -6.566]",8,"(-23.007, -21.409]",10,"(7.312, 8.041]",7,"(-0.086, 0.0242]",16,"(45.292, 55.882]",31,...,"(87.15, 88.969]",11.0,"(30.884, 36.73]",33.0,"(7.13, 7.249]",12.0,"(809.434, 827.44]",38.0,"(-0.001, 0.00177]",0.0
11,"(-12.906, -11.526]",3,"(-30.12, -28.838]",5,"(3.739, 4.741]",3,"(-0.634, -0.52]",11,"(55.882, 102.181]",32,...,"(96.692, 97.964]",17.0,"(30.884, 36.73]",33.0,"(7.249, 7.343]",13.0,"(809.434, 827.44]",38.0,"(-0.001, 0.00177]",0.0
12,"(2.71, 3.516]",18,"(-8.327, -7.133]",20,"(12.722, 13.884]",14,"(0.0242, 0.128]",17,"(15.262, 17.018]",20,...,"(104.443, 105.838]",23.0,"(30.884, 36.73]",33.0,"(8.099, 8.162]",24.0,"(789.351, 809.434]",37.0,"(-0.001, 0.00177]",0.0
13,"(-2.759, -1.62]",12,"(-21.409, -19.687]",11,"(11.653, 12.722]",13,"(1.685, 1.858]",31,"(14.151, 15.262]",19,...,"(99.45, 100.803]",19.0,"(30.884, 36.73]",33.0,"(8.016, 8.099]",23.0,"(754.343, 770.845]",35.0,"(-0.001, 0.00177]",0.0
14,"(-4.265, -2.759]",11,"(-23.007, -21.409]",10,"(10.499, 11.653]",12,"(1.188, 1.294]",27,"(8.209, 9.419]",14,...,"(93.662, 95.223]",15.0,"(27.275, 29.056]",31.0,"(7.805, 7.88]",20.0,"(700.736, 719.115]",32.0,"(-0.001, 0.00177]",0.0
15,"(-7.488, -6.566]",8,"(-24.569, -23.007]",9,"(5.705, 6.522]",5,"(0.353, 0.481]",20,"(18.161, 19.788]",22,...,"(95.223, 96.692]",16.0,"(23.809, 25.438]",29.0,"(7.745, 7.805]",19.0,"(655.457, 677.943]",30.0,"(-0.001, 0.00177]",0.0
16,"(-4.265, -2.759]",11,"(-19.687, -17.857]",12,"(9.173, 9.8]",10,"(-0.634, -0.52]",11,"(36.378, 40.008]",29,...,"(83.159, 84.441]",8.0,"(22.286, 23.809]",28.0,"(7.343, 7.415]",14.0,"(655.457, 677.943]",30.0,"(-0.001, 0.00177]",0.0
17,"(-6.566, -5.42]",9,"(-28.838, -27.314]",6,"(8.041, 8.595]",8,"(-0.634, -0.52]",11,"(55.882, 102.181]",32,...,"(78.904, 81.305]",6.0,"(22.286, 23.809]",28.0,"(6.648, 6.758]",7.0,"(614.8, 640.857]",28.0,"(-0.001, 0.00177]",0.0
18,"(5.675, 6.576]",21,"(-4.104, -3.28]",24,"(19.031, 20.224]",19,"(-0.783, -0.634]",10,"(5.509, 6.688]",12,...,"(76.676, 78.904]",5.0,"(20.654, 22.286]",27.0,"(6.363, 6.512]",5.0,"(614.8, 640.857]",28.0,"(-0.001, 0.00177]",0.0
19,"(3.516, 4.503]",19,"(-11.594, -10.363]",17,"(21.561, 22.606]",21,"(-0.306, -0.212]",14,"(21.333, 23.344]",24,...,"(81.305, 83.159]",7.0,"(20.654, 22.286]",27.0,"(6.172, 6.363]",4.0,"(551.317, 581.637]",26.0,"(0.00879, 0.0248]",2.0

In [65]:
all_processed_df = pd.concat([all_processed_df,binned_df], axis=1)
all_processed_df.head()

,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,...,Percent_of_Normal_Precip_Rolling_Average_Binned,Percent_of_Normal_Precip_Rolling_Average_Binned_Encoded,Snow_on_Ground_Rolling_Average_Binned,Snow_on_Ground_Rolling_Average_Binned_Encoded,Days_with_Precip_Rolling_Average_Binned,Days_with_Precip_Rolling_Average_Binned_Encoded,Heating_Degree_Days_Rolling_Average_Binned,Heating_Degree_Days_Rolling_Average_Binned_Encoded,Cooling_Degree_Days_Rolling_Average_Binned,Cooling_Degree_Days_Rolling_Average_Binned_Encoded
0,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
all_processed_df.columns.name = 'Climate ID'
all_processed_df.head()

Climate ID,Mean_Temp,Min_Temp,Max_Temp,Mean_Diff_from_Normal,Snowfall,Percent_of_Normal_Snowfall,Total_Precip,Percent_of_Normal_Precip,Snow_on_Ground,Days_with_Precip,...,Percent_of_Normal_Precip_Rolling_Average_Binned,Percent_of_Normal_Precip_Rolling_Average_Binned_Encoded,Snow_on_Ground_Rolling_Average_Binned,Snow_on_Ground_Rolling_Average_Binned_Encoded,Days_with_Precip_Rolling_Average_Binned,Days_with_Precip_Rolling_Average_Binned_Encoded,Heating_Degree_Days_Rolling_Average_Binned,Heating_Degree_Days_Rolling_Average_Binned_Encoded,Cooling_Degree_Days_Rolling_Average_Binned,Cooling_Degree_Days_Rolling_Average_Binned_Encoded
0,0.351884,-8.668497,8.602305,1.891500,18.861538,36.088106,107.797911,63.116071,19.377926,11.515625,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-4.457322,-18.166109,8.743096,6.969307,4.954146,16.724138,5.833195,22.025210,6.722222,1.784232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-8.665789,-24.729032,4.388312,6.291262,6.587407,34.563636,7.125000,35.327586,28.449541,2.681250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-12.049573,-29.186325,2.558974,5.515873,10.712821,43.716049,10.385294,45.918605,41.987179,3.875000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-7.284188,-24.331624,2.815385,1.800800,42.976410,87.454545,46.653304,72.245902,35.673469,10.585903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
all_processed_df.to_csv('datasets/climate_dimension_binned.csv')